Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,10 +35,8 @@ jobs:
 
       - name: Decode Keystore
         env:
-          ENCODED_STRING: ${{ secrets.KEYSTORE_BASE_64 }}
-          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
-          RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
-          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
+          USERNAME_PROD: ${{ secrets.USERNAME_PROD }}
+          PASSWORD_PROD: ${{ secrets.PASSWORD_PROD }}
         run: |
           echo $ENCODED_STRING > keystore-b64.txt
           base64 -d keystore-b64.txt > keystore.jks
@@ -48,6 +46,13 @@ jobs:
           USERNAME_PROD: ${{ secrets.USERNAME_PROD }}
           PASSWORD_PROD: ${{ secrets.PASSWORD_PROD }}
         run: ./gradlew assembleRelease --stacktrace
+
+      - name: Verify APK file presence
+        run: |
+          if [ ! -f app/build/outputs/apk/release/app-release.apk ]; then
+            echo "Signed APK file not found!"
+            exit 1
+          fi
 
       - name: Build Release bundle
         env:
@@ -61,7 +66,7 @@ jobs:
 
       - name: Get release file apk path
         id: releaseApk
-        run: echo "apkfile=$(find app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT
+        run: echo "apkfile=$(find app/build/outputs/apk/release/app-release.apk)" >> $GITHUB_OUTPUT
 
       - name: Zip Files
         uses: papeloto/action-zip@v1
@@ -69,24 +74,8 @@ jobs:
           files: ${{ steps.releaseAab.outputs.aabfile }} ${{ steps.releaseApk.outputs.apkfile }}
           dest: ${{ steps.releaseApk.outputs.apkfile }}.zip
 
-#      - name: Sending release build to Slack
-#        uses: MeilCli/slack-upload-file@v3
-#        with:
-#          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
-#          file_path: ${{ steps.releaseApk.outputs.apkfile }}.zip
-#          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
-#          initial_comment: "Release build is now available."
-#
-#      - name: upload apk to Firebase App Distribution
-#        uses: wzieba/Firebase-Distribution-Github-Action@v1
-#        with:
-#          appId: ${{secrets.FIREBASE_APP_ID_RELEASE}}
-#          serviceCredentialsFileContent: ${{ secrets.SERVICE_CREDENTIALS_FILE_RELEASE }}
-#          groups: ${{ github.event.inputs.testers }}
-#          file: ${{ steps.releaseApk.outputs.apkfile }}
-
       - name: Upload Release Build to Artifacts
         uses: actions/upload-artifact@v3
         with:
            name: release-artifacts
-           path: ${{ steps.releaseApk.outputs.apkfile }}
+           path: ${{ steps.releaseApk.outputs.apkfile }}.zip
