Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,7 +14,7 @@ on:
         required: true
         default: 'test'
         options:
-          - test
+          - test  # Solo permite "test" como opción válida
 
 jobs:
   build-production:
@@ -41,9 +41,17 @@ jobs:
           unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
           mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
           export ANDROID_SDK_ROOT=$HOME/android-sdk
-          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
+          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/build-tools/33.0.3
           yes | sdkmanager --licenses
           sdkmanager "build-tools;33.0.3" "platforms;android-33"
+
+      - name: Debug Android SDK structure
+        run: |
+          echo "ANDROID_SDK_ROOT is set to: $ANDROID_SDK_ROOT"
+          ls -R $ANDROID_SDK_ROOT
+
+      - name: Verify apksigner
+        run: which apksigner || echo "apksigner not found"
 
       - name: Set up environment variables for production build
         run: |
@@ -65,21 +73,47 @@ jobs:
         run: |
           sed -i 's/applicationId "com.kt.webconteinerapp"/applicationId "${{ env.APPLICATION_ID }}"/' app/build.gradle
 
+      - name: Debug environment variables
+        run: printenv
+
       - name: Build the app
+        shell: bash
         env:
           SERVICE_USERNAME: ${{ env.SERVICE_USERNAME }}
           PASSWORD: ${{ env.PASSWORD }}
+          DOMAIN_SERVER_SUC: ${{ env.DOMAIN_SERVER_SUC }}
+          DOMAIN_USER: ${{ env.DOMAIN_USER }}
+          SIGNING_KEY_ALIAS: ${{ env.SIGNING_KEY_ALIAS }}
+          SIGNING_KEY_PASSWORD: ${{ env.SIGNING_KEY_PASSWORD }}
+          SIGNING_STORE_PASSWORD: ${{ env.SIGNING_STORE_PASSWORD }}
         run: ./gradlew assembleRelease --info --stacktrace -x lint
+
+      - name: List APKs
+        run: |
+          for file in app/build/outputs/apk/release/*; do
+            echo "Found file: $file"
+          done
 
       - name: Sign the APK
         run: |
-          $ANDROID_SDK_ROOT/build-tools/33.0.3/apksigner sign --ks TabKT1.jks --ks-pass pass:${{ env.SIGNING_STORE_PASSWORD }} --key-pass pass:${{ env.SIGNING_KEY_PASSWORD }} --out app/build/outputs/apk/release/${{ env.APK_NAME }} app/build/outputs/apk/release/app-release-unsigned.apk
+          $ANDROID_SDK_ROOT/build-tools/33.0.3/apksigner sign \
+          --ks TabKT1.jks \
+          --ks-pass pass:${{ env.SIGNING_STORE_PASSWORD }} \
+          --key-pass pass:${{ env.SIGNING_KEY_PASSWORD }} \
+          --out app/build/outputs/apk/release/${{ env.APK_NAME }} \
+          app/build/outputs/apk/release/app-release-unsigned.apk
+
+      - name: Verify APK Signature
+        run: |
+          $ANDROID_SDK_ROOT/build-tools/33.0.3/apksigner verify \
+          app/build/outputs/apk/release/${{ env.APK_NAME }}
 
       - name: Upload build artifacts
         uses: actions/upload-artifact@v3
         with:
           name: production-apk
           path: app/build/outputs/apk/release/${{ env.APK_NAME }}
+          if-no-files-found: error
 
   build-testing:
     runs-on: ubuntu-latest
